### ISSUE TITLE
Custom marker's icon doesn't get shown

### ISSUE THREAD

**Issue by mmazurovsky** [gonuit/google_static_maps_flutter#13]
Hello!

First of all, I want to thank you for such a convenient plugin.

I have only one problem which is connected with the custom marker icon. When I try to use my link for the icon, for example, "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/apple/285/round-pushpin_1f4cd.png", it doesn't show on the map. The default google's red marker is shown instead without any logs appearing in the debug console.

In the example provided in the plugin page on the pub.dev you use the link shortened by google shortening link service which is no longer available as I can see. So I can't really create the link with such pattern: "https://goo.gl/******".

Could you please help?

**Comment by gonuit** [comment]
### Hi @mmazurovsky!
First of all, thank you for opening this issue.
I will look at this today and will back to you with a solution 💪🏻.
Stay tuned 😃.

**Comment by mmazurovsky** [comment]
> ### Hi @mmazurovsky!
> First of all, thank you for opening this issue.
> I will look at this today and will back to you with a solution 💪🏻.
> Stay tuned 😃.

Hello @gonuit !
Do you have any updates on the issue?

**Comment by VladanRandjelovic** [comment]
Hello @gonuit, I have the same bug, and I saw this issue opened, but no solution yet. Is it going to be anytime soon? If so thank you so much, since that one is road blocker for me currently

**Comment by timgrossmann** [comment]
Hi @gonuit :) 
Any chance we could get an update on this?
We are using this in our app and would love have this fixed.

Would really appreciate a response.
Thanks

**Comment by gonuit** [comment]
Hi guys! 👋🏻 
Sorry for the late reply, I was very busy in the last few months 😞.
I'm working on the fix. Stay tuned 🎤 ⏲️ (one more time).

**Comment by gonuit** [comment]
## So! I have good and bad news for you😅.

### good information 👍🏻 
The **good** information is that the marker's custom icons should works correctly as the generated URL matches google static maps documentation.
### bad information 👎🏻 
So the problem is probably with provided icons. 😨
### Few tips:
- Your icon cannot be larger than `64 x 64` pixels.
  I know it can be confusing at times, but Google **NOT** supports larger icons. The documentation says that:
  > Icons may be up to 4096 pixels maximum size (64x64 for square images)
  
  **Therefore `image_width * image_height <= 4096`.**
- The file must be accessible to the google static maps API.
- Make sure the file is not corrupted or in an unsupported format (`png` is preferred, but` GIF` and `JPEG` will also work)
- Only `5` different icons can be used for a single map image (multiple locations can be defined for each icon)
___
If this does not fix your issue, feel free to reopen it and provide me with an example icon that does not work for you 🕵🏻.
Have a nice day! 👋🏻
